apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: database
  labels:
    app: database
spec:
  containers:
  - name: mysql
    resources:
      requests:
        cpu: 200m
        memory: 0.5Gi
      limits:
        cpu: 400m
        memory: 1Gi
    image: mysql:5.7
    ports:
    - name: mysql-port
      containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: database-secrets
            key: rootPassword
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: database-secrets
            key: username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: database-secrets
            key: password
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: database-secrets
            key: database
