# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
  namespace: dev
spec:
  rules:
  - host: dev-v1.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: app-v1
          servicePort: 80
  - host: dev-latest.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: app-latest
          servicePort: 80
